### ISSUE TITLE
issue installing a mod

### ISSUE THREAD

**Issue by noyikoo** [Argent77/A7-add_kit_ex#6]
Hello,

I have an error  installing a mod which is a Stalker revision from Artisan Kitpack. Artemiusl the owner of the mod told me to contact you.
I try to install the mod in BG2EE Steam version, no other mod installed. I select French language.

The message from Artemius :
'' a7#add_kit_ex.tpa is a script made by argent77, not me. It's possible the language has something to do with it because I cannot reproduce any issues on an English game. You'll have to bring up an issue [here](https://github.com/Argent77/A7-add_kit_ex) because the stalker component shouldn't even use anything from that script since it isn't adding a new kit so there's something wrong with the script itself. '

This is the error I get :

''Installing [Artisan's Kitpack: Stalker Overhaul] [4.6]
In state 1402, I expected one of these tokens:
[38] PLUS
[64] LT
[80] MINUS
[107] BASR
[136] RPAREN
[138] GT
[151] BXOR
[162] DIVIDE
[198] BLSR
[223] BOR
[229] BLSL
[246] MODULO
[250] QUESTION
[253] TIMESTIMES
[298] OR
[319] AND
[330] TIMES
[338] EQUALSEQUALS
[361] LTE
[392] BAND
[415] EQUALS
[434] GTE
[436] NOTEQUALS
Parse error (state 1402) at ~~

[ArtisansKitpack/lib/a7#add_kit_ex.tpa] PARSE ERROR at line 1423 column 1-56
Near Text: %clab_resref%.2DA
GLR parse error

[ArtisansKitpack/lib/a7#add_kit_ex.tpa] ERROR at line 1423 column 1-56
Near Text: %clab_resref%.2DA
Parsing.Parse_error
ERROR: parsing [ArtisansKitpack/lib/a7#add_kit_ex.tpa]: Parsing.Parse_error
Stopping installation because of error.

ERROR Installing [Artisan's Kitpack: Stalker Overhaul], rolling back to previous state
Will uninstall 0 files for [ARTISANSKITPACK/ARTISANSKITPACK.TP2] component 2011.
Uninstalled 0 files for [ARTISANSKITPACK/ARTISANSKITPACK.TP2] component 2011.
In state 1402, I expected one of these tokens:
[38] PLUS
[64] LT
[80] MINUS
[107] BASR
[136] RPAREN
[138] GT
[151] BXOR
[162] DIVIDE
[198] BLSR
[223] BOR
[229] BLSL
[246] MODULO
[250] QUESTION
[253] TIMESTIMES
[298] OR
[319] AND
[330] TIMES
[338] EQUALSEQUALS
[361] LTE
[392] BAND
[415] EQUALS
[434] GTE
[436] NOTEQUALS
Parse error (state 1402) at ~~

[ArtisansKitpack/lib/a7#add_kit_ex.tpa] PARSE ERROR at line 1423 column 1-56
Near Text: %clab_resref%.2DA
GLR parse error

[ArtisansKitpack/lib/a7#add_kit_ex.tpa] ERROR at line 1423 column 1-56
Near Text: %clab_resref%.2DA
Parsing.Parse_error
ERROR: parsing [ArtisansKitpack/lib/a7#add_kit_ex.tpa]: Parsing.Parse_error
Error Uninstalling [ARTISANSKITPACK/ARTISANSKITPACK.TP2] component 2011:
Parsing.Parse_error
ERROR: Parsing.Parse_error
Please make a backup of the file: SETUP-ARTISANSKITPACK.DEBUG and look for support at: Artemius_''

Thank you in advance

**Comment by noyikoo** [comment]
For the follow up, I confirm this is French language which prevented to install the kit mod. I solved the problem by installing subrace mod first. I selected French language when I installed subrace mod, then when I launched Artisan kitpack mod I did not have to select a language again.

**Comment by Argent77** [comment]
This is not a language-specific issue. Instead, by installing another mod first you have probably (inadvertently) fixed the issue on your local installation because of WeiDU's auto-update feature.

About the original issue:
That's not directly an error in the a7#add_kit_ex library itself. @ArtemiusI included an outdated WeiDU installer binary (v246) in the Artisan's Kitpack archive. However, the library uses functionality that requires at least v247 of the WeiDU installer. This is mentioned in the readme. But I will also add this note to the library file itself to increase visibility.

Apart from fixing it indirectly by using the auto-update feature from mods that ship with a newer WeiDU version, you can also update the installer manually:
- Open the [WeiDU Releases](https://github.com/WeiDUorg/weidu/releases/latest) page and download the zip file that matches your system.
- Unpack the downloaded zip file to a temporary folder.
- Look for a file called `weidu.exe` and rename it to `setup-ArtisansKitpack.exe`.
- Overwrite the original binary from Artisan's Kitpack with the new file and restart the mod installation.

**Comment by noyikoo** [comment]
Thank you for your answer and the explanation
